"""Error codes used across WS frames and REST responses.

Keep in sync with spec §7.
"""

AUTH_FAIL = "AUTH_FAIL"
FILE_TOO_LARGE = "FILE_TOO_LARGE"
UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
QUEUE_FULL = "QUEUE_FULL"
AUDIO_DURATION_OUT_OF_RANGE = "AUDIO_DURATION_OUT_OF_RANGE"
DECODE_FAILED = "DECODE_FAILED"
INFERENCE_TIMEOUT = "INFERENCE_TIMEOUT"
INFERENCE_ERROR = "INFERENCE_ERROR"
PARTIAL_PARSE = "PARTIAL_PARSE"  # warning, not error
SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
DISK_FULL = "DISK_FULL"
INTERNAL = "INTERNAL"
NOT_FOUND = "NOT_FOUND"
EXPIRED = "EXPIRED"
